import type { Metadata } from "next";
import Link from "next/link";
import { Check, ArrowRight } from "lucide-react";

const url = "https://unifiedbrandingexperts.com/dropshipping-growth-plans";
export const metadata: Metadata = {
  title: "Dropshipping Growth Plans | 90 Days, 6 Months, 12 Months",
  description: "Explore longer-term store management, AI SEO and social marketing plans after launch. Compare work, support, timelines and costs with UBE.",
  alternates: { canonical: url },
};

// Proposed commercial terms. Do not publish before owner confirmation.
const plans = [
  { title: "90-day launch & learn", duration: "3 months", total: "$4,000", management: "$1,500", ai: "$1,000", social: "$1,500", focus: "Set the baseline, launch content and campaigns, learn which products and channels show traction." },
  { title: "6-month optimization", duration: "6 months", total: "$7,000", management: "$2,700", ai: "$1,800", social: "$2,500", focus: "Continue the winning experiments and improve product pages, search coverage, supplier fit and retention." },
  { title: "12-month managed growth", duration: "12 months", total: "$11,800", management: "$4,800", ai: "$3,000", social: "$4,000", focus: "Maintain the catalog and campaigns while reviewing seasonality, vendor expansion and repeat purchase opportunities." },
];

export default function DropshippingGrowthPlansPage() {
  return (
    <div className="mx-auto max-w-7xl space-y-14 px-4 pb-24 pt-32 sm:px-6 md:px-12">
      <nav aria-label="Breadcrumb" className="text-sm"><Link href="/" className="underline">Home</Link> / <Link href="/dropshipping-store-offer" className="underline">Store offer</Link> / Managed growth plans</nav>
      <header className="max-w-3xl space-y-5"><span className="font-mono-num text-xs font-bold uppercase tracking-widest text-[#6049B0]">After the storefront</span><h1 className="font-display text-4xl font-bold sm:text-6xl">Keep building after launch.</h1><p className="text-lg leading-relaxed text-[#414141]">Store management, AI SEO and social marketing work together on the catalog, discovery and demand. Choose a 90-day, six-month or 12-month planning horizon, then agree the exact channels and deliverables in your written scope.</p></header>
      <section aria-labelledby="plan-heading" className="space-y-6"><h2 id="plan-heading" className="font-display text-3xl font-bold">Three ways to work together</h2><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.duration} className="rounded-[2rem] border border-[#D8CFEB] bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-[#6049B0]">{plan.duration}</p><h3 className="mt-2 font-display text-2xl font-bold">{plan.title}</h3><p className="mt-3 text-3xl font-bold text-[#161616]">{plan.total}<span className="ml-1 text-sm font-normal text-[#585858]">for the term</span></p><dl className="mt-5 grid gap-2 border-t border-[#E0DDDB] pt-4 text-sm"><div className="flex justify-between gap-3"><dt>Store management</dt><dd>{plan.management}</dd></div><div className="flex justify-between gap-3"><dt>AI SEO</dt><dd>{plan.ai}</dd></div><div className="flex justify-between gap-3"><dt>Social marketing</dt><dd>{plan.social}</dd></div></dl><p className="mt-5 text-sm leading-relaxed text-[#414141]">{plan.focus}</p></article>)}</div><p className="text-sm text-[#585858]">Prices cover the stated service term, not monthly payments. Paid media budget, platform fees, apps, product inventory and production costs are separate. Campaign channel mix and creative approval are agreed before work begins.</p></section>
      <section className="grid gap-8 rounded-[2rem] bg-[#F2ECFA] p-6 lg:grid-cols-2 lg:p-10"><div><h2 className="font-display text-3xl font-bold">What the ongoing work includes</h2><p className="mt-3 text-[#414141]">A dedicated point of contact coordinates specialists and reviews the plan with you. The workflow adapts to product availability, account access and actual campaign data.</p></div><ul className="grid gap-3 text-sm text-[#303030]">{["Update the store and upload up to 50 agreed product listings per month, subject to usable source data and rights.", "Review suppliers and vendors, fulfillment constraints, catalog accuracy and new product candidates.", "Plan and produce up to 10 approved social posts and 10 short-form reels per month from supplied or scoped assets.", "Improve technical and on-page SEO, answer-focused content, internal links and eligible structured data.", "Configure and manage an agreed mix of Meta, Instagram or TikTok campaigns; Google Ads can be scoped where the budget and products fit.", "Report on traffic, spending, qualified leads, orders and product economics during biweekly review meetings.", "Provide agreed live calls, chat and email support through a dedicated manager, with response hours set in the agreement."].map((item) => <li key={item} className="flex gap-2"><Check className="h-5 w-5 shrink-0 text-[#6049B0]" />{item}</li>)}</ul></section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-[2rem] border border-[#E0DDDB] bg-white p-6"><h2 className="font-display text-2xl font-bold">How we define results</h2><p className="mt-3 text-sm leading-relaxed text-[#414141]">Our first 60 days establish the baseline and test the route to recovering the agreed investment. We review attributable sales against spend and service cost. A particular ROI, number of orders or profit level cannot be promised without a contract defining the starting point, budget, dependencies, measurement and remedy. The signed scope controls any specific performance commitment.</p></div><div className="rounded-[2rem] border border-[#E0DDDB] bg-white p-6"><h2 className="font-display text-2xl font-bold">Start with the right foundation</h2><p className="mt-3 text-sm leading-relaxed text-[#414141]">These ongoing plans follow an existing or newly built store. If you need a storefront first, compare the <Link href="/dropshipping-store-offer" className="font-semibold text-[#6049B0] underline">launch offer</Link>. For a different operational scope, review <Link href="/ecommerce-store-management-packages" className="font-semibold text-[#6049B0] underline">standard management packages</Link>.</p><Link href="/contact?type=dropshipping-growth" className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#9F8BE7] px-6 font-bold text-[#161616]">Discuss a growth plan <ArrowRight className="h-4 w-4" /></Link></div></section>
    </div>
  );
}
